name: ML

dependencies:
  - python=3.6
  - jupyter
  - scikit-learn
  - pandas
  - matplotlib
  - plotly
  - seaborn
  - numpy=1.15
  - tqdm
  - scipy
  - sympy
  - tensorflow=1.11
  - bokeh
  - anaconda::graphviz
  - pip
